version: 1.8.10.{build}
configuration: Release
init:
- cmd: ''
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: nuget restore
build:
  project: Ketarin.csproj
  verbosity: minimal
after_build:
- cmd: >-
    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.dll

    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.exe

    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.config
artifacts:
- path: bin\Release\Ketarin.exe
- path: bin\Release\Ketarin.exe.config
- path: bin\Release\Microsoft.Management.Infrastructure.dll
- path: bin\Release\ScintillaNET.dll
- path: bin\Release\System.Data.SQLite.DLL
- path: bin\Release\System.Management.Automation.DLL
- path: bin\Release\Tamir.SharpSSH.dll